### ISSUE TITLE
CRAN release?

### ISSUE THREAD

**Issue by mstaniak** [psobczyk/varclust#9]
Any chance you're going to upload the package to CRAN?

I would love to use it as a dependency in my package for the automatic selection of number of clusters, but I can't because of lack of CRAN version.

**Comment by sjwilczynski** [comment]
Maybe @psobczyk knows something on this topic. For now I can say that the paper is being finished and afterwards the package will be submitted as soon as possible. However, it is hard to give an estimate

**Comment by psobczyk** [comment]
From my side we are good to go. I just need to confirm this with all  co-authors

**Comment by psobczyk** [comment]
@mstaniak On CRAN :)
